//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backup.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backup.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Windows Backup as dataes (WPF .NET) , Developer Mahdi Khayamdar.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Select Source Data   2-Select Path Backup   3-Choose Backup &amp; Backup Ai .
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string MenuBackup {
            get {
                return ResourceManager.GetString("MenuBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Ai.
        /// </summary>
        public static string MenuBackupAi {
            get {
                return ResourceManager.GetString("MenuBackupAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuCloseApp {
            get {
                return ResourceManager.GetString("MenuCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete List Data.
        /// </summary>
        public static string MenuDelDocs {
            get {
                return ResourceManager.GetString("MenuDelDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string MenuEdu {
            get {
                return ResourceManager.GetString("MenuEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Backup.
        /// </summary>
        public static string MenuPath {
            get {
                return ResourceManager.GetString("MenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Backup.
        /// </summary>
        public static string MenuStop {
            get {
                return ResourceManager.GetString("MenuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of data to backup.
        /// </summary>
        public static string TitleGpList {
            get {
                return ResourceManager.GetString("TitleGpList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Process.
        /// </summary>
        public static string TitleGpProcess {
            get {
                return ResourceManager.GetString("TitleGpProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup as data.
        /// </summary>
        public static string ToolTipBackup {
            get {
                return ResourceManager.GetString("ToolTipBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup adavnced.
        /// </summary>
        public static string ToolTipBackupAi {
            get {
                return ResourceManager.GetString("ToolTipBackupAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop backup.
        /// </summary>
        public static string TooltipCancel {
            get {
                return ResourceManager.GetString("TooltipCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete List Data .
        /// </summary>
        public static string ToolTipDelete {
            get {
                return ResourceManager.GetString("ToolTipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path save backup.
        /// </summary>
        public static string ToolTipPath {
            get {
                return ResourceManager.GetString("ToolTipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder for backup.
        /// </summary>
        public static string ToolTipSelect {
            get {
                return ResourceManager.GetString("ToolTipSelect", resourceCulture);
            }
        }
    }
}
